#' Copy a (work)sheet
#'
#' Copies a (work)sheet, within its current (spread)Sheet or to another Sheet.
#'
#' @eval param_ss(pname = "from_ss")
#' @eval param_sheet(
#'   pname = "from_sheet",
#'   action = "copy",
#'   "Defaults to the first visible sheet."
#' )
#' @param to_ss The Sheet to copy *to*. Accepts all the same types of input as
#'   `from_ss`, which is also what this defaults to, if unspecified.
#' @param to_sheet Not implemented yet. But once it is: Name of the new sheet,
#'   as a string. If you don't specify this, Google generates a name, along the
#'   line of "Copy of blah". Note that sheet names must be unique within a
#'   Sheet, so if the automatic name would violate this, Google also
#'   de-duplicates it for you, e.g. "Copy of blah 2". If you have strong
#'   opinions about these matters, you should specify `to_sheet`.
#' @param .before Not implemented yet.
#' @param .after Not implemented yet.
#'
#' @return The receiving Sheet, `to_ ss`, as an instance of [`sheets_id`].
#' @export
#' @family worksheet functions
#' @seealso
#' If the copy happens within one Sheet, makes a `DuplicateSheetRequest`:
#'   * <https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#duplicatesheetrequest>
#'
#' If the copy is from one Sheet to another, wraps the
#' `spreadsheets.sheets/copyTo` endpoint:
#' * <https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo>
#'
#' @examples
#' if (sheets_has_token()) {
#'   ss_aaa <- sheets_create(
#'     "sheets-sheet-copy-demo-aaa",
#'     sheets = list(iris = head(iris), chickwts = head(chickwts))
#'   )
#'
#'   # copy 'iris' sheet within existing Sheet, accept autogenerated name
#'   ss_aaa %>%
#'     sheets_sheet_copy()
#'
#'   # copy 'iris' sheet within existing Sheet
#'   # specify new sheet's name and location
#'   ss_aaa %>%
#'     sheets_sheet_copy(to_sheet = "iris-the-sequel", .after = 1)
#'
#'   # make a second Sheet
#'   ss_bbb <- sheets_create("sheets-sheet-copy-demo-bbb")
#'
#'   # copy 'chickwts' sheet from first Sheet to second
#'   ss_aaa %>%
#'     sheets_sheet_copy("chickwts", to_ss = ss_bbb)
#'
#'   # copies 'chickwts' sheet from first Sheet to second WITH a specific name
#'   # and into a specific location
#'   # NOTE: NAME ANd LOCATION PART NOT IMPLEMENTED YET
#'   ss_aaa %>%
#'     sheets_sheet_copy(
#'       "chickwts",
#'       to_ss = ss_bbb, to_sheet = "chicks-two", .after = 0
#'     )
#'
#'   # clean up
#'   googledrive::drive_find("sheets-sheet-copy-demo") %>%
#'     googledrive::drive_trash()
#' }
sheets_sheet_copy <- function(from_ss,
                              from_sheet = NULL,
                              to_ss = from_ss,
                              to_sheet = NULL,
                              .before = NULL,
                              .after = NULL) {
  from_ssid <- as_sheets_id(from_ss)
  to_ssid <- as_sheets_id(to_ss)
  maybe_sheet(from_sheet)

  if (identical(from_ssid, to_ssid)) {
    sheets_sheet_copy_internal(
      ssid       = from_ssid,
      from_sheet = from_sheet,
      to_sheet   = to_sheet,
      .before    = .before,
      .after     = .after
    )
  } else {
    sheets_sheet_copy_external(
      from_ssid  = from_ssid,
      from_sheet = from_sheet,
      to_ssid    = to_ssid,
      to_sheet   = to_sheet,
      .before    = .before,
      .after     = .after
    )
  }
}

sheets_sheet_copy_internal <- function(ssid,
                                       from_sheet = NULL,
                                       to_sheet = NULL,
                                       .before = NULL,
                                       .after = NULL) {
  maybe_string(to_sheet)
  x <- sheets_get(ssid)
  s <- lookup_sheet(from_sheet, sheets_df = x$sheets)
  message_glue("Duplicating sheet {dq(s$name)} in {dq(x$name)}")

  dup_request <- new(
    "DuplicateSheetRequest",
    sourceSheetId =s$id
  )
  if (!is.null(.before) || !is.null(.after)) {
    dup_request <- patch(
      dup_request,
      insertSheetIndex = resolve_index(
        x$sheets, .before = .before, .after = .after
      )
    )
  }
  if (!is.null(to_sheet)) {
    dup_request <- patch(dup_request, newSheetName = to_sheet)
  }

  req <- request_generate(
    "sheets.spreadsheets.batchUpdate",
    params = list(
      spreadsheetId = ssid,
      requests = list(duplicateSheet = dup_request)
    )
  )
  resp_raw <- request_make(req)
  resp <- gargle::response_process(resp_raw)
  to_name <- pluck(resp, "replies", 1, "duplicateSheet", "properties", "title")
  message_glue("Copied as {dq(to_name)}")

  invisible(ssid)
}

sheets_sheet_copy_external <- function(from_ssid,
                                       from_sheet = NULL,
                                       to_ssid,
                                       to_sheet = NULL,
                                       .before = NULL,
                                       .after = NULL) {
  from_x <- sheets_get(from_ssid)
  to_x   <- sheets_get(to_ssid)
  from_s <- lookup_sheet(from_sheet, sheets_df = from_x$sheets)
  message_glue(
    "Copying sheet {dq(from_s$name)} from {dq(from_x$name)} to {dq(to_x$name)}"
  )

  req <- request_generate(
    "sheets.spreadsheets.sheets.copyTo",
    params = list(
      spreadsheetId = from_ssid,
      sheetId = from_s$id,
      destinationSpreadsheetId = as.character(to_ssid)
    )
  )
  resp_raw <- request_make(req)
  to_s <- gargle::response_process(resp_raw)
  message_glue("Copied as {dq(to_s$title)}")

  invisible(to_ssid)
}
